refactor Dockerfile
kubeshop/testkube-argocd pull request #4
Opened 2022-06-17 08:30 UTC by ypoplavs

- decreased Docker image size;
- added error handling for the script

## Changes

-

## Fixes

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-06-17 08:46 UTC, vsukhin approved these changes

2022-06-18 05:21 UTC, exu approved these changes

2022-06-18 19:34 UTC, aabedraba approved these changes
nice stuff!

2022-06-20 08:58 UTC, nicufk approved these changes

2022-06-20 14:16 UTC, chlete requested changes

2022-06-20 14:16 UTC, chlete commented on Dockerfile
> + && curl -L "https://github.com/kubeshop/testkube/releases/download/v$VERSION/testkube_${VERSION}_${PLATFORM}.tar.gz" | tar -xzvf - \
```suggestion
 && curl -L "https://github.com/kubeshop/testkube/releases/download/v${VERSION}/testkube_${VERSION}_${PLATFORM}.tar.gz" | tar -xzvf - \
```

2022-06-20 14:41 UTC, ypoplavs commented on Dockerfile
> + && curl -L "https://github.com/kubeshop/testkube/releases/download/v$VERSION/testkube_${VERSION}_${PLATFORM}.tar.gz" | tar -xzvf - \
great attention to detail, Christian!

2022-06-20 15:07 UTC, merged